<a href="https://colab.research.google.com/github/RonakkudalAI/Practical-Machine-Learning/blob/main/Basic_Operation_(Day1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

List = List is Hetrogeneous, order, mutable, and duplicate allowed


In [ ]:
lst = ["Pizza","Burger","Pasta","Chole Bhature","Dhokla"]
lst


['Pizza', 'Burger', 'Pasta', 'Chole Bhature', 'Dhokla']

In [ ]:

lst.append("Dal Bati")
lst

['Pizza', 'Burger', 'Pasta', 'Chole Bhature', 'Dhokla', 'Dal Bati']

In [ ]:
lst.extend(["Coke","Smooth"])
lst

['Pizza',
 'Burger',
 'Pasta',
 'Chole Bhature',
 'Dhokla',
 'Dal Bati',
 'Coke',
 'Smooth']

In [ ]:
#Remove - Remove element by using Name
lst.remove("Burger")
lst

['Pizza', 'Pasta', 'Chole Bhature', 'Dhokla', 'Dal Bati', 'Coke', 'Smooth']

In [ ]:
lst.pop()
lst

['Pizza', 'Pasta', 'Chole Bhature', 'Dhokla', 'Dal Bati', 'Coke']

In [ ]:
lst.append("Pasta")
lst

['Pizza', 'Pasta', 'Chole Bhature', 'Dhokla', 'Dal Bati', 'Coke', 'Pasta']

In [ ]:
#Remove First occurance Element
lst.remove("Pasta")
lst

['Pizza', 'Chole Bhature', 'Dhokla', 'Dal Bati', 'Coke', 'Pasta']

In [ ]:
#Delete element by Index
lst.pop(2) #Dhokla is deleted
lst

['Pizza', 'Chole Bhature', 'Dal Bati', 'Coke', 'Pasta']

In [ ]:
lst_Slice = lst[:2]
lst_Slice

['Pizza', 'Chole Bhature']

In [ ]:
for i in lst:
  print(i)

Pizza
Chole Bhature
Dal Bati
Coke
Pasta


In [ ]:
upper_case = [item.upper() for item in lst]
upper_case

['PIZZA', 'CHOLE BHATURE', 'DAL BATI', 'COKE', 'PASTA']

Dictionary : Key-Value , heterogenous , no order , mutable and duplicate key not not allowed


In [ ]:
customer = {
    "Name":["Ronak","Shivam","Rahul"],
    "City" :["Udaipur","Mp","Jaipu"],
    "Age" : [20,22,24]
}
customer

{'Name': ['Ronak', 'Shivam', 'Rahul'],
 'City': ['Udaipur', 'Mp', 'Jaipu'],
 'Age': [20, 22, 24]}

In [ ]:
customer['Name']

['Ronak', 'Shivam', 'Rahul']

In [ ]:
customer.get('Age')

[20, 22, 24]

In [ ]:
for key,value in customer.items():
  print(key,value)

Name ['Ronak', 'Shivam', 'Rahul']
City ['Udaipur', 'Mp', 'Jaipu']
Age [20, 22, 24]


In [ ]:
del customer["Age"]


In [ ]:
customer

{'Name': ['Ronak', 'Shivam', 'Rahul'], 'City': ['Udaipur', 'Mp', 'Jaipu']}

Sets : Unordered , Unique, not mutable

In [ ]:
cusines = {"Indian","Chinese","Italian","Indian"}
cusines

{'Chinese', 'Indian', 'Italian'}

In [ ]:
cusines.add("Mexican")
cusines

{'Indian', 'Italian', 'Mexian', 'Mexican'}

In [ ]:
cusines.discard("Chinese")
cusines

{'Indian', 'Italian', 'Mexian', 'Mexican'}

In [ ]:
cusines_set1  = {"Indian","Chinese","Italian"}
cusines_set2 = {"Mexican","Chinese","Italian"}

In [ ]:
cusines_set1.union(cusines_set2)

{'Chinese', 'Indian', 'Italian', 'Mexican'}

In [ ]:
cusines_set1.intersection(cusines_set2)

{'Chinese', 'Italian'}

Tuples: Set of Elements, ordered, immutable


In [ ]:
location = (19.0700,72.73763)
location

(19.07, 72.73763)

In [ ]:
lat,lon = location #unpacking
print(lat, lon)

19.07 72.73763


In [ ]:
t1 = (1,)#Single value declaration in tuple
t1

(1,)

Case Study for dataset


In [ ]:
Order = {
    "Order_id" :101,
    "Customer":{
        "name":"Ronak",
        "Age":20,
        "City":"Udaipur"
    },
    "item":["Pizza","Pasta","Burger"],
   "cusiens":{"Italian","Indian"},
    "location" : (19.0700,72.73763)

}

In [ ]:
print(Order["Customer"]["Age"])

20


In [ ]:
print(Order["item"][0])

Pizza


In [ ]:
print(Order["cusiens"])

{'Italian', 'Indian'}


In [ ]:
Order["Customer"].pop("Age")

20

In [ ]:
Order["item"].pop(1)
Order

{'Order_id': 101,
 'Customer': {'name': 'Ronak', 'City': 'Udaipur'},
 'item': ['Pizza', 'Burger'],
 'cusiens': {'Indian', 'Italian'},
 'location': (19.07, 72.73763)}

In [ ]:
Order["item"].append("Dhokla")
Order

{'Order_id': 101,
 'Customer': {'name': 'Ronak', 'City': 'Udaipur'},
 'item': ['Pizza', 'Burger', 'Dhokla'],
 'cusiens': {'Indian', 'Italian'},
 'location': (19.07, 72.73763)}

In [ ]:
Order["cusiens"].add("Gujrati")

In [ ]:
Order["item"].insert(0,"Chole Bhature")
Order

{'Order_id': 101,
 'Customer': {'name': 'Ronak', 'City': 'Udaipur'},
 'item': ['Chole Bhature', 'Pizza', 'Burger', 'Dhokla'],
 'cusiens': {'Gujrati', 'Indian', 'Italian'},
 'location': (19.07, 72.73763)}

In [ ]:
import pandas as pd
dtypes = pd.DataFrame({
    'Type': ['int8', 'uint8', 'int16', 'uint16', 'int32', 'uint32',
             'int64', 'uint64', 'float16', 'float32', 'float64',
             'float128', 'complex64', 'complex128', 'bool',
             'object', 'string_', 'unicode_'],
    'Type Code': ['i1', 'u1', 'i2', 'u2', 'i4', 'u4',
                  'i8', 'u8', 'f2', 'f4 or f', 'f8 or d',
                  'f16 or g', 'c8', 'c16', '',
                  'O', 'S', 'U']
})
dtypes

,Type,Type Code
0,int8,i1
1,uint8,u1
2,int16,i2
3,uint16,u2
4,int32,i4
5,uint32,u4
6,int64,i8
7,uint64,u8
8,float16,f2
9,float32,f4 or f


In [ ]:
import numpy as np
arr = np.array([12,14,16],dtype ='f4')
arr

array([12., 14., 16.], dtype=float32)

In [ ]:
arr.dtype

dtype('float32')

In [ ]:
np.array([1+2j,2-4j],dtype=np.complex64)

array([1.+2.j, 2.-4.j], dtype=complex64)

In [ ]:
np.array([0,1,1],dtype=bool)

array([False,  True,  True])

In [ ]:
np.array([0,1,1],dtype=np.bool_)

array([False,  True,  True])

In [ ]:

str = np.array(['yug','abc'],dtype = 'S3')
str

array([b'yug', b'abc'], dtype='|S3')

Series-1 D lablelled array that can store multiple data types

In [ ]:
s1=pd.Series([1,"Amit",3.5,"Hello"])
s1

,0
0,1
1,Amit
2,3.5
3,Hello


In [ ]:
#Custom Index
s1=pd.Series([1,"Amit",3.5,"Hello"],index=["a","b","c","d"])
s1


,0
a,1
b,Amit
c,3.5
d,Hello


In [ ]:
emp = {"amit":1000,"sai":40000,"ram":50000,"Tom":80000}
emp = pd.Series(emp)
emp

,0
amit,1000
sai,40000
ram,50000
Tom,80000


In [ ]:
student={
    "Name":["Amit","Bob","Tom"],
    "Marks":[78,56,89]
}
df = pd.DataFrame(student)

In [ ]:
df["Grade"]=["A","B","C"]
df

,Name,Marks,Grade
0,Amit,78,A
1,Bob,56,B
2,Tom,89,C


In [ ]:
df = df.drop('Grade',axis=1)
df

,Name,Marks
0,Amit,78
1,Bob,56
2,Tom,89


In [ ]:
df.rename(columns={'Name':'Title'},inplace =True)
df

,Title,Marks
0,Amit,78
1,Bob,56
2,Tom,89


In [ ]:
df["Marks"] = df['Marks'].apply(lambda x:x+5)
df

,Title,Marks
0,Amit,83
1,Bob,61
2,Tom,94


In [ ]:
student={
    "Name":["Amit","Bob","Tom","Jerry","Tanmay","Ranu"],
    "Marks":[78,56,89,85,71,68]
}
df = pd.DataFrame(student)
df

,Name,Marks
0,Amit,78
1,Bob,56
2,Tom,89
3,Jerry,85
4,Tanmay,71
5,Ranu,68


In [ ]:
df["High_Marks"] = df["Marks"] > 85
df

,Name,Marks,High Marks,High_Marks
0,Amit,False,False,False
1,Bob,False,False,False
2,Tom,False,False,False
3,Jerry,False,False,False
4,Tanmay,False,False,False
5,Ranu,False,False,False
